#!/usr/bin/env python3
"""Aggregate local session CSV exports into a feature matrix for modeling.

Input: CSV files under analysis/session_data generated by the app export
Output: analysis/session_features_local.csv with one row per session

The target y is set to the session score (game score). Accuracy stays as a feature.
"""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Dict, List, Optional

DATA_DIR = Path(__file__).parent / "session_data"
OUT_PATH = Path(__file__).parent / "session_features_local.csv"


def parse_float(value: Optional[str]) -> Optional[float]:
    if value is None:
        return None
    try:
        return float(value)
    except (ValueError, TypeError):
        return None


def parse_header(lines: List[str]) -> Dict[str, str]:
    """Parse the comment header of one export file into a flat dict."""
    meta: Dict[str, str] = {}
    for line in lines:
        if not line.startswith("#"):
            # Skip blank lines until we reach the CSV body
            if line.strip() == "":
                continue
            break
        stripped = line.lstrip("#").strip()
        if not stripped or stripped.startswith("---"):
            continue
        if ":" not in stripped:
            continue
        key, value = stripped.split(":", 1)
        meta[key.strip()] = value.strip()
    return meta


def build_row(meta: Dict[str, str]) -> Dict[str, object]:
    targets = meta.get("Targets Hit")
    targets_hit = total_targets = None
    if targets and "/" in targets:
        hit_part, total_part = targets.split("/", 1)
        targets_hit = parse_float(hit_part)
        total_targets = parse_float(total_part)

    duration = parse_float(meta.get("Duration (s)"))
    time_per_target = None
    if duration and total_targets:
        time_per_target = duration / total_targets if total_targets else None

    accuracy = parse_float(meta.get("Accuracy (%)"))
    score = parse_float(meta.get("Score"))

    # Screen size parsing (e.g., "2560x1328")
    screen_size = meta.get("Screen Size")
    screen_width = screen_height = None
    if screen_size and "x" in screen_size:
        width_str, height_str = screen_size.split("x", 1)
        screen_width = parse_float(width_str)
        screen_height = parse_float(height_str)

    row = {
        "sessionId": meta.get("Session ID"),
        "sessionDate": meta.get("Session Date"),
        "participantLabel": meta.get("Participant Label"),
        "consentAccepted": meta.get("Consent Accepted"),
        "consentTimestamp": meta.get("Consent Timestamp"),
        "surveyAgeCheck": meta.get("Survey Age Check"),
        "surveyWebcamCheck": meta.get("Survey Webcam Check"),
        "gamesPlayed": meta.get("Survey Games Played"),
        "mainGame": meta.get("Survey Main Game"),
        "mainGameOther": meta.get("Survey Main Game (Other)"),
        "aimTrainerUsage": meta.get("Survey Aim Trainer Usage"),
        "inGameRank": meta.get("Survey Rank") or meta.get("Survey In-Game Rank"),
        "playTime": meta.get("Survey Play Time"),
        "selfAssessment": parse_float(meta.get("Survey Self-Assessment")),
        "calibrationStatus": meta.get("Calibration Status"),
        "validationError_px": parse_float(meta.get("Validation Error (px)")),
        "validationStdDev_px": parse_float(meta.get("Validation Avg. StdDev (px)")),
        "calibrationCompletedAt": meta.get("Calibration Completed At"),
        "screenSize": screen_size,
        "screenWidth": screen_width,
        "screenHeight": screen_height,
        "score": score,
        "accuracy": accuracy,
        "mouseAccuracy": parse_float(meta.get("Mouse Accuracy (%)")),
        "gazeAccuracy": parse_float(meta.get("Gaze Accuracy (%)")),
    }
    row.update(
        {
            "avgReactionTime_ms": parse_float(meta.get("Avg Reaction Time (ms)")),
            "gazeAimLatency_ms": parse_float(meta.get("Gaze Aim Latency (ms)")),
            "duration_s": duration,
            "targetsHit": targets_hit,
            "totalTargets": total_targets,
            "timePerTarget_s": time_per_target,
            "y_performance": score,  # target label = game score
        }
    )
    return row


def collect_rows() -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    for path in sorted(DATA_DIR.glob("*.csv")):
        with path.open(encoding="utf-8") as f:
            lines = f.readlines()
        meta = parse_header(lines)
        if not meta:
            continue
        rows.append(build_row(meta))
    return rows


def main() -> None:
    rows = collect_rows()
    if not rows:
        print("No session files found under analysis/session_data.")
        return

    fieldnames = [
        "sessionId",
        "sessionDate",
        "participantLabel",
        "consentAccepted",
        "consentTimestamp",
        "surveyAgeCheck",
        "surveyWebcamCheck",
        "gamesPlayed",
        "mainGame",
        "mainGameOther",
        "aimTrainerUsage",
        "inGameRank",
        "playTime",
        "selfAssessment",
        "calibrationStatus",
        "validationError_px",
        "validationStdDev_px",
        "calibrationCompletedAt",
        "screenSize",
        "screenWidth",
        "screenHeight",
        "score",
        "accuracy",
        "mouseAccuracy",
        "gazeAccuracy",
        "avgReactionTime_ms",
        "gazeAimLatency_ms",
        "duration_s",
        "targetsHit",
        "totalTargets",
        "timePerTarget_s",
        "y_performance",
    ]

    with OUT_PATH.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"Wrote {len(rows)} sessions to {OUT_PATH}")


if __name__ == "__main__":
    main()
